### ISSUE TITLE
Throws Error on anything - won't execute.

### ISSUE THREAD

**Issue by examinedliving** [MarkTiedemann/anydo-cli#1]
Running on Windows 7 64bit with Node v5.11.0.

Running anything returns: 
```
C:\Users\Daniel\AppData\Roaming\npm\node_modules\anydo-cli\node_modules\anydo\index.js:7
const login = ({
ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Daniel\AppData\Roaming\npm\node_modules\anydo-cli\bin.js:3:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by MarkTiedemann** [comment]
This is because Node 5 does not support [default parameters](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Default_parameters) (which are used in the `anydo` module).

Thus, in order to use this CLI, please upgrade to at least Node 6.

PS: You should probably upgrade anyways since Node 5 has no [LTS](https://github.com/nodejs/LTS).

I'd recommend using a Node Version Manager to easily upgrade and switch between different Node versions. See: [`nvm`](https://github.com/creationix/nvm) or [`nvm-windows`](https://github.com/coreybutler/nvm-windows).
